const code = {
  VALUE_REQUIRED: 'required',
  INVALID_LAST_NAME: 'invalidLastName',
  INVALID_FIRST_NAME: 'invalidFirstName',
  INCORRECT_DATE: 'incorrectDateFormat',
  INVALID_SINGLE_VIP_POLICYHOLDER_DOB: 'invalidSingleVIPPolicyHolderDOB',
  INVALID_POLICYHOLDER_DOB: 'invalidPolicyHolderDOB',
  INVALID_SINGLE_VIP_ADULT_DOB: 'invalidSingleVIPAdultDOB',
  INVALID_ADULT_DOB: 'invalidAdultDOB',
  INVALID_CHILD_DOB: 'invalidChildDOB',
  INVALID_PHONE_NUMBER: 'invalidPhoneNumber',
  INVALID_EMAIL: 'invalidEmail',
  EMAIL_TOO_LONG: 'emailTooLong',
  INVALID_STAFF_EMAIL: 'invalidStaffEmail',
  EMAIL_NOT_MATCH: 'emailDoNotMatch',
  INVALID_ADDRESS: 'invalidAddress',
  ADDRESS_TOO_LONG: 'addressTooLong',
  INVALID_DISTRICT: 'invalidDistrict',
  INVALID_TRAVEL_TYPE: 'invalidTravelType',
  INVALID_STARTDATE: 'invalidStartDate',
  STARTDATE_OVER_LIMIT: 'startDateOverLimit',
  INVALID_END_DATE: 'invalidEndDate',
  ENDDATE_OVER_LIMIT: 'endDateOverLimit',
  ENDDATE_SHOULD_BE_ONE_YEAR: 'invalidAnnualEndDate',
  INVALID_NUMBER_OF_ADULT: 'invalidNumberOfAdult',
  INVALID_NUMBER_OF_ADULT_FOR_FAMILY: 'invalidNumberOfAdultForFamily',
  INVALID_NUMBER_OF_MAIN_INSURED: 'invalidNumberOfMainInsured',
  INVALID_NUMBER_OF_SPOUSE: 'invalidNumberOfSpouse',
  INVALID_NUMBER_OF_CHILDREN: 'invalidNumberOfChildren',
  INVALID_PROMO_CODE: 'invalidPromoCode',
  INVALID_CURRENCY: 'invalidCurrency'
};

export default code;
