version: '3'
services:
  web:
    command: yarn start
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN}
        NODE_ENV: production
    ports:
    - "3000:8080"
    environment:
    - NODE_ENV=uat
    container_name: fe-travel-docker-compose
    volumes:
    - "./src:/opt/app-root/src"
